name: Automated Code Review
on:
  pull_request:
    branches: [ "main" ]

jobs:
  checkstyle-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: 'warning'
          # Quan trọng: Dòng này sẽ làm pipeline đỏ lòm nếu có bất kỳ lỗi format nào
          fail_on_error: true